# Generated by Django 5.2.10 on 2026-01-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0002_proof_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
