# Generated by Django 5.2.10 on 2026-01-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donation'},
        ),
    ]
