# Generated by Django 5.2.10 on 2026-01-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0002_alter_donation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOTrust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.IntegerField(default=0)),
                ('total_donations', models.IntegerField(default=0)),
                ('total_proofs_approved', models.IntegerField(default=0)),
                ('ngo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ngos.ngo')),
            ],
        ),
    ]
